name: Update the Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./API/
          file: ./API/Dockerfile
          push: true
          tags: gladou/pe_api:1.0.${{ github.run_number}}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./API/database/
          file: ./API/database/Dockerfile
          push: true
          tags: gladou/pe_db:1.0.${{ github.run_number}}
